[coffe][ngspice] enabled use of ngspice in place of hspice
StephenMoreOSU/rad_gen pull request #5
Opened 2024-08-14 19:20 UTC by robluo

In the spiceintergace.run() function, the use of hspice and ngspice is hardcoded. A command line option is needed.

2024-08-20 17:27 UTC, StephenMoreOSU reviewed
lgtm

Would change the cli arg to be like "spice_sim_type" and pass in "hspice" or "ngspice" but for now the boolean (use ngspice vs don't use ngspice) is fine.

2024-08-20 21:29 UTC, vaughnbetz requested changes
Some suggested changes; mostly adding some more comments (especially high level ones) and type annotations. You should also add a simple / fast test of rad-sim properly writing out and simulating something with ngspice to the short test script that Stephen has (or will) list as the fast test people should run when making a change.

2024-08-20 21:29 UTC, vaughnbetz commented on src/coffe/spice.py
> +        class circuit:
Explain the overall flow of this routine and it's purpose. I've read the code and have a general idea, but it isn't that easy to figure out exactly what it's goal or method is.

2024-08-20 21:29 UTC, vaughnbetz commented on src/coffe/spice.py
> +    def run_ngspice(self, sp_path, parameter_dict):
Add type annotations.

2024-08-20 21:29 UTC, vaughnbetz commented on src/coffe/spice.py
> +        """
Great docstring!

2024-08-20 21:29 UTC, vaughnbetz commented on src/coffe/spice.py
> +        # functions used by regex subsititution
I suggest adding a comment with a list of the changes to the .sp file needed by ngspice. You kind of have that in the comments below, but giving a concise summary would be helpful.

2024-08-21 00:08 UTC, StephenMoreOSU commented on src/common/data_structs.py
> +    ngspice: bool # use ngspice over default hspice
This was what my comment was mentioning as well. It would actually be a good thing to get it put in now while we're thinking about it.

2024-09-17 19:04 UTC, merged